#!/bin/bash

password=$(echo "" | dmenu)
eval $(echo $password | op signin my)

selection=$(
	op list items | 
	jq '.[] | .overview.title, .uuid' | 
	sed 's/"//g' |
	sed 'N;s/\n/ /' |
	sort | 
	dmenu -i -l 20 -fn Monospace-14
)

if [ -z "$selection" ]; then
    exit 1
fi

uuid=$(echo $selection | awk 'NF{ print $NF }')

op get item $uuid |
jq '.details.fields[] | select(.designation=="password").value' |
sed 's/"//g' |
xclip -sel clip

